import Link from "next/link";
import {Container} from "@/components/Container";

export default function HarbourTransferPage() {
  const harbours = [
      {
            id: "padangbai",
                  name: "Padangbai Harbour",
                        icon: "🚢",
                              description: "Pintu gerbang utama penyeberangan feri dan fast boat menuju ke Pulau Lombok, Gili Trawangan, dan sekitarnya.",
                                    slug: "/harbour-transfer/padangbai",
                                        },
                                            {
                                                  id: "sanur",
                                                        name: "Sanur Harbour",
                                                              icon: "⛵",
                                                                    description: "Pelabuhan fast boat terpopuler untuk penyeberangan cepat menuju Nusa Penida dan Nusa Lembongan.",
                                                                          slug: "/harbour-transfer/sanur",
                                                                              },
                                                                                  {
                                                                                        id: "gilimanuk",
                                                                                              name: "Gilimanuk Harbour",
                                                                                                    icon: "⛴️",
                                                                                                          description: "Pelabuhan penyeberangan feri utama di Bali barat yang menghubungkan Bali dengan Pulau Jawa (Ketapang).",
                                                                                                                slug: "/harbour-transfer/gilimanuk",
                                                                                                                    },
                                                                                                                      ];

                                                                                                                        return (
                                                                                                                            <div className="min-h-screen bg-navy-900 text-white flex flex-col justify-between selection:bg-yellow-500 selection:text-black">
                                                                                                                                  {/* HEADER / NAVBAR SEDERHANA */}
                                                                                                                                        <header className="border-b border-white/10 py-4">
                                                                                                                                                <Container className="flex items-center justify-between">
                                                                                                                                                          <Link href="/" className="flex items-center gap-2">
                                                                                                                                                                      <span className="text-lg font-bold tracking-wider">BAT</span>
                                                                                                                                                                                  <span className="text-xs text-gray-400 hidden sm:inline">| Bali Airport Transfer</span>
                                                                                                                                                                                            </Link>
                                                                                                                                                                                                      <Link 
                                                                                                                                                                                                                  href="/" 
                                                                                                                                                                                                                              className="text-sm text-gray-300 hover:text-yellow-400 transition-colors"
                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                    &larr; Kembali ke Beranda
                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                      </Container>
                                                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                                                  {/* KONTEN UTAMA */}
                                                                                                                                                                                                                                                                                        <main className="flex-grow py-12 px-4">
                                                                                                                                                                                                                                                                                                <Container>
                                                                                                                                                                                                                                                                                                          <div className="max-w-2xl mx-auto text-center mb-12">
                                                                                                                                                                                                                                                                                                                      <span className="text-xs uppercase tracking-widest text-yellow-500 bg-yellow-500/10 px-3 py-1 rounded-full border border-yellow-500/20 font-medium">
                                                                                                                                                                                                                                                                                                                                    Pilih Pelabuhan Penjemputan / Tujuan
                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                            <h1 className="text-3xl md:text-4xl font-bold mt-4 mb-3 tracking-tight">
                                                                                                                                                                                                                                                                                                                                                                          Harbour Transfer Across Bali
                                                                                                                                                                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-400 text-sm md:text-base leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                Pilih pelabuhan penyeberangan Anda untuk melihat rute tujuan lengkap dengan harga tetap yang transparan dan supir profesional berbahasa Inggris.
                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* GRID PILIHAN HARBOUR */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {harbours.map((harbour) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={harbour.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href={harbour.slug}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="group bg-navy-800/60 border border-white/10 hover:border-yellow-500/50 rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 shadow-xl flex flex-col justify-between"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-4xl mb-4 p-3 bg-white/5 w-fit rounded-xl border border-white/5 group-hover:scale-110 transition-transform">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {harbour.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-xl font-bold mb-2 group-hover:text-yellow-400 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {harbour.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-400 text-sm leading-relaxed mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {harbour.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center justify-between pt-4 border-t border-white/10 text-sm font-semibold text-yellow-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>Lihat Destinasi & Harga</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="group-hover:translate-x-1 transition-transform">&rarr;</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* FOOTER */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <footer className="py-6 border-t border-white/10 text-center text-xs text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              &copy; {new Date().getFullYear()} Bali Airport Transfer. Safe, Reliable, Comfortable.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
