import Image from "next/image";
import { fleet } from "@/data/fleet";

export default function Fleet() {
  return (
      <section className="bg-white py-20">
            <div className="mx-auto max-w-7xl px-6">

                    <div className="mb-12 text-center">
                              <p className="text-sm font-semibold uppercase tracking-widest text-[#D4AF37]">
                                          Our Fleet
                                                    </p>

                                                              <h2 className="mt-3 text-3xl font-bold text-[#08142B] md:text-4xl">
                                                                          Comfortable Vehicles For Every Journey
                                                                                    </h2>

                                                                                              <p className="mx-auto mt-4 max-w-2xl text-gray-600">
                                                                                                          Choose the right vehicle for your airport transfer needs in Bali.
                                                                                                                    </p>
                                                                                                                            </div>


                                                                                                                                    <div className="grid gap-8 md:grid-cols-3">

                                                                                                                                              {fleet.map((vehicle) => (
                                                                                                                                                          <div
                                                                                                                                                                        key={vehicle.name}
                                                                                                                                                                                      className="
                                                                                                                                                                                                    overflow-hidden
                                                                                                                                                                                                                  rounded-3xl
                                                                                                                                                                                                                                border
                                                                                                                                                                                                                                              border-gray-100
                                                                                                                                                                                                                                                            bg-white
                                                                                                                                                                                                                                                                          shadow-lg
                                                                                                                                                                                                                                                                                        transition
                                                                                                                                                                                                                                                                                                      hover:-translate-y-2
                                                                                                                                                                                                                                                                                                                    "
                                                                                                                                                                                                                                                                                                                                >

                                                                                                                                                                                                                                                                                                                                              <div className="relative h-56 w-full">

                                                                                                                                                                                                                                                                                                                                                              <Image
                                                                                                                                                                                                                                                                                                                                                                                src={vehicle.image}
                                                                                                                                                                                                                                                                                                                                                                                                  alt={vehicle.name}
                                                                                                                                                                                                                                                                                                                                                                                                                    fill
                                                                                                                                                                                                                                                                                                                                                                                                                                      className="object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rounded-full
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bg-[#08142B]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          px-4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            py-2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text-xs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                font-semibold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text-[#D4AF37]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {vehicle.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="mt-5 text-xl font-bold text-[#08142B]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {vehicle.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h3>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-3 text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {vehicle.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-5 space-y-2 text-sm">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                👥 {vehicle.passengers}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        🧳 {vehicle.luggage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mt-6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                w-full
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rounded-xl
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bg-[#D4AF37]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      py-3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-semibold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-[#08142B]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              hover:bg-[#c49f2f]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Book This Vehicle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }